### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by jzdynamo**
This is a huge change, that includes the fixes of around 1000-2000 lint errors. Half of them are done by auto fix and half are done manually.

Most manually-addressed errors are in the following categories:
1. http://eslint.org/docs/rules/no-unused-vars
2. http://eslint.org/docs/rules/no-use-before-define
3. http://eslint.org/docs/rules/eqeqeq
4. http://eslint.org/docs/rules/consistent-return

You can see the full list of errors when you run `npm run lint` in current master branch.

I have disabled many less-important rules. If you are interested, please see the change in .eslintrc.json (the "rules" section)

I also enabled react/jsx support for eslint so that it can parse jsx syntax.

I may probably introduce some bugs during the fixing. I just did some smoke testing after the fix, but I'm not 100% sure that everything works exactly as before. But I really did the refactoring very very carefully to ensure that nothing is broken.

## Most Importantly
**Please enable the eslint checking in your IDE or editor** 

My IDE is Atom, and I've enabled eslint by installing this package: https://atom.io/packages/linter-eslint. The eslint UI will automatically work after your installing the package and restart Atom. The IDE will follow the rules we defined in .eslintrc.json.

ESlint are also supported by IntelliJ, WebStorm, Sublime Text, Emacs, etc. Please enable it because it can not only help unifying our coding style, but also help us early detect potential bugs (using an undefined variable for example). Actually I've seen some bugs during fixing the lint errors.

Please kindly review or take a look. I hope we can merge it soon before producing much conflict.

@wpzero

### CODE REVIEW

**Comment by jzdynamo** [comment]
Another thing is, due to this rule http://eslint.org/docs/rules/no-use-before-define, I changed the order of some methods' definition, whose diffs are most hard-to-read ones. So you may not see the order change clearly in the pull request. But when you see large diff blocks, don't worry. I didn't change any logic. Those diff blocks are just produced by reordering. :)

**Comment by wpzero** [comment]
@jzdynamo Amazing job, I like eslint,  but I try to use eslint, ``npm run lint``, output some errors, I don't know What wrong. and I run ``npm run develop`` , It didn't run successfully,  I don't know if u run it successfully?

**Comment by jzdynamo** [comment]
@wpzero do you mind sharing the commit hash you are on? And also show some screenshots about the errors?

**Comment by jzdynamo** [comment]
Did u run `npm install` btw?

**Pull request closed without merging**
